---

- name: Autoremove unneeded packages installed as dependencies
  yum:
    autoremove: yes

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"

- name: Transfer template file to the remote machines
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

...
